### ISSUE TITLE
docker-compose 启动失败

### ISSUE THREAD

**Issue by machooo-x** [linux-do/override#16]
![image](https://github.com/linux-do/override/assets/50037831/eed492fe-b7ed-44c5-bbef-9d0dff7ad3ba)

使用docker部署时,卡在这里, 是什么问题啊?
步骤:

拉取代码 https://github.com/linux-do/override.git

docker-compose up 启动

**Comment by dong152389** [comment]
我也是卡在这里了

**Comment by wozulong** [comment]
网络不通畅
