### ISSUE TITLE
idea github copilot chat 接口报错

### ISSUE THREAD

**Issue by zhangwt-cn** [linux-do/override#18]
### idea
<img width="574" alt="image" src="https://github.com/linux-do/override/assets/52098594/93ed5bcc-51e7-4cc5-b34d-ffd7a2cb28e8">

### 接口日志
```bash
2024/05/17 17:31:24 request completions failed: {
  "error": {
    "message": "Unknown parameter: 'intent_threshold'.",
    "type": "invalid_request_error",
    "param": "intent_threshold",
    "code": "unknown_parameter"
  }
}
[GIN] 2024/05/17 - 17:31:24 | 400 |         1m54s |       127.0.0.1 | POST     "/v1/chat/completions"

```
### 请求参数
```json
{
    "messages": [
        {
            "role": "system",
            "content": ""
        },
        {
            "role": "user",
            "content": ""
        },
        {
            "role": "system",
            "content": "."
        },
        {
            "role": "user",
            "content": "1"
        }
    ],
    "model": "gpt-4o",
    "max_tokens": 6108,
    "temperature": 0,
    "top_p": 1,
    "n": 1,
    "stream": true,
    "intent_threshold": 0.9,
    "intent_content": "1"
}
```

看日志应该是`intent_threshold`问题， 始皇有空帮忙看看，非常感谢😊

**Comment by donaldturinglee** [comment]
补全代码请用Completions模型，例如：gpt-3.5-turbo-instruct，而不是chat模型

**Comment by zhanghaotian2018** [comment]
@zhangwt-cn  我拉取了最新版， 我的还是这个报错。 你的解决了吗

**Comment by zhangwt-cn** [comment]
> @zhangwt-cn 我拉取了最新版， 我的还是这个报错。 你的解决了吗

我的已经解决了

**Comment by zhanghaotian2018** [comment]
> > @zhangwt-cn 我拉取了最新版， 我的还是这个报错。 你的解决了吗
> 
> 我的已经解决了

需要做什么操作吗？ 谢谢

**Comment by zhangwt-cn** [comment]
> > > @zhangwt-cn 我拉取了最新版， 我的还是这个报错。 你的解决了吗
> > 
> > 
> > 我的已经解决了
> 
> 需要做什么操作吗？ 谢谢
<img width="523" alt="image" src="https://github.com/linux-do/override/assets/52098594/783cca5b-1428-4b32-bd60-6bfbad2430d0">
正常情况下这段代码已经把这几个字段删除了。你可以贴一下错误信息、日志以及配置看下

**Comment by zhanghaotian2018** [comment]
> > > > @zhangwt-cn 我拉取了最新版， 我的还是这个报错。 你的解决了吗
> > > 
> > > 
> > > 我的已经解决了
> > 
> > 
> > 需要做什么操作吗？ 谢谢
> 
> <img alt="image" width="523" src="https://private-user-images.githubusercontent.com/52098594/331953187-783cca5b-1428-4b32-bd60-6bfbad2430d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODUxODgsIm5iZiI6MTcxNjE4NDg4OCwicGF0aCI6Ii81MjA5ODU5NC8zMzE5NTMxODctNzgzY2NhNWItMTQyOC00YjMyLWJkNjAtNmJmYmFkMjQzMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA2MDEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTljZTRjZjI2ZDFiMjA3OGQ0MDRjMjY3NWJkOWNlYzEzYzUzZGI0MGE3MGNmMjUxN2E3OTM0YzZlYWY2YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6EIjxL2dha9zrnwxseTK2JL3dnFdLuZi9SEn1dbrbI8"> 正常情况下这段代码已经把这几个字段删除了。你可以贴一下错误信息、日志以及配置看下

感谢 已解决
