### ISSUE TITLE
"codex_max_tokens": 4093, 没生效。

### ISSUE THREAD

**Issue by zhanghaotian2018** [linux-do/override#19]
版本：最新

"codex_max_tokens": 4093,已配置
![image](https://github.com/linux-do/override/assets/169218899/4fbc58df-fd9c-481d-aaff-8beb5f77c048)

已重启。

日志：
![image](https://github.com/linux-do/override/assets/169218899/5dad3e09-bf17-4506-9570-b18072a0e716)

**Comment by wozulong** [comment]
> ![Clip_2024-05-18_13-15-08](https://private-user-images.githubusercontent.com/59789646/331767525-9005bcd8-9fde-4d79-8b41-b8df20bd3715.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMzQ3MzYsIm5iZiI6MTcxNjAzNDQzNiwicGF0aCI6Ii81OTc4OTY0Ni8zMzE3Njc1MjUtOTAwNWJjZDgtOWZkZS00ZDc5LThiNDEtYjhkZjIwYmQzNzE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEyMTM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjBmM2Y2Mzk0ZTc1ZDA1MzYyZGY4MTU5NGUzMzIwZDg2NzMyNDNhZjdhOTAzMDVmM2M4M2MwZTQ3YTkwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7uvc0kyU2ba9avk9enf34OC86vPDETfqTSfalreegjk) 同上 idea

你这个是另一个问题，已经修复。

**Comment by wozulong** [comment]
最新版已硬改。
