### ISSUE TITLE
copilot 打开补全面板不支持

### ISSUE THREAD

**Issue by heheda123123** [linux-do/override#28]
当按 `ctrl-enter` 打开建议列表的时候
![image](https://github.com/linux-do/override/assets/97490782/d8e41fa8-8fd1-4a6f-a2c9-e2f8b09d9ec5)

会出现如下错误，是否可以支持上这个呢
![image](https://github.com/linux-do/override/assets/97490782/e36ee49e-a6b7-4ad9-acfe-9f8fecb3d33b)

**Comment by wozulong** [comment]
这是 new-api 的问题，我来修复一下。

**Comment by wozulong** [comment]
oaipro 已修复，new-api 仓库我也推上去了

**Comment by heheda123123** [comment]
> oaipro 已修复，new-api 仓库我也推上去了

咦，忘说了，我不是用的oaipro，是用的另外的api代理商。这个问题从override代码层面处理不了吗？

**Comment by wozulong** [comment]
处理不了，因为 new-api 里把这个字段当作 bool 了，但是 /v1/completions 这个字段是 int | null。

所以只能在 new-api 里兼容这个字段到更多类型。否则这个字段也就失去作用了

**Comment by heheda123123** [comment]
ok
