### ISSUE TITLE
安装异常

### ISSUE THREAD

**Issue by lnts2015-1** [linux-do/override#38]
docker build -t override-app .
Sending build context to Docker daemon  160.3kB
Step 1/10 : FROM golang:alpine AS builder
alpine: Pulling from library/golang
d25f557d7f31: Pulling fs layer 
8b732c871fea: Pulling fs layer 
060aaf7efd06: Pulling fs layer 
7d1964877d68: Waiting 
4f4fb700ef54: Waiting 
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/28/288827cf059ed530cf2400518e01f3841781c178c483ecbe1be7816efb581aa7/data?verify=1718626438-0ToXUy9ZDtvibsL3B6Dc06jXCDI%3D: dial tcp 103.240.180.117:443: i/o timeout

感谢大佬。

**Comment by forose** [comment]
加代理就可以了

**Comment by forose** [comment]
可以看看pr里有一个我的  用那个Dockerfile是可以的

**Comment by zhanghaotian2018** [comment]
> 可以看看pr里有一个我的 用那个Dockerfile是可以的

看到了 感谢

**Comment by lnts2015-1** [comment]
> 可以看看pr里有一个我的 用那个Dockerfile是可以的

收到 感谢。
