### ISSUE TITLE
请问一下这个代码补全是存在bug吗是不是做不到原版的效果

### ISSUE THREAD

**Issue by duolabmeng6** [linux-do/override#40]
![image](https://github.com/linux-do/override/assets/59047063/b13892cb-9e3b-4a15-ab6d-748f5fd8e4e6)
我使用了ollama run stable-code:code 
还有 deepseek-coder 也是这种情况 请问一下是普遍的现象吗 还是我们需要加入一些提示词来解决这个问题 

谢谢大佬的好项目 先说声谢谢大佬了

**Comment by wwh1004** [comment]
copilot的codex模型是私有的，公开的模型没有那个效果。不是提示词的问题。copilot用的补全接口是旧的openapi格式接口，支持插入模式，发过去的全部内容就等于是完整提示词了。
