### ISSUE TITLE
docker hub中找不到linux-do/override

### ISSUE THREAD

**Issue by nadirvishun** [linux-do/override#56]
pull时返回错误：`! override-app Warning pull access denied for linux-do/override, repository does not exist or may require...`
然后取docker hub中取找，发现没有，但是原先应该是有的，我这次更新才发现不见了。

**Comment by nadirvishun** [comment]
哦，原先应该也是自动编译的。

**Comment by MurphyZX** [comment]
我也遇到了 请问要怎么操作一下呢？

**Comment by nadirvishun** [comment]
> 我也遇到了 请问要怎么操作一下呢？

试试`docker compose up -d --build`来重新编译呢？或者不行的话就先把旧image删除掉，再运行试试
